v97
arkenfox/user.js pull request #1346
Opened 2022-01-24 07:41 UTC by Thorin-Oakenpants

- 0605: see https://bugzilla.mozilla.org/show_bug.cgi?id=1355460

2022-02-05 19:22 UTC, szepeviktor commented
> * 0605: see [bugzilla.mozilla.org/show_bug.cgi?id=1355460](https://bugzilla.mozilla.org/show_bug.cgi?id=1355460)

Mozilla guys are very tricky!

2022-02-05 19:41 UTC, Thorin-Oakenpants commented
> Mozilla guys are very tricky!

I don't see an issue. About the only time I think this would trigger without you wanting to actually visit is when you left click to drag and drop. I only added it to be consistent

2022-02-11 11:29 UTC, Thorin-Oakenpants commented
am done with #1366 and ready to merge - awaiting reviews

2022-02-11 14:43 UTC, fxbrit commented on user.js
> + * [SETUP-WEB] SSL_ERROR_UNSAFE_NEGOTIATION: is it worth overriding this for that one site
add a question mark maybe?

2022-02-11 15:10 UTC, fxbrit approved these changes

2022-02-11 16:52 UTC, GlassGruber commented
> > Mozilla guys are very tricky!
> 
> I don't see an issue. About the only time I think this would trigger without you wanting to actually visit is when you left click to drag and drop. I only added it to be consistent

Wouldn't this be triggered when reordering bookmarks?

2022-02-11 16:57 UTC, Thorin-Oakenpants commented
> Wouldn't this be triggered when reordering bookmarks?

IDK and don't care, I disabled it :) I use a speed dial for my stuff, otherwise my toolbar has
- three folders and then four bookmarks - i never need to reorder anything - the rest of the space on the toolbar if for drg n drop URLs for me to follow up on etc
- i never use the bookmarks manager

So that's what I meant when I said drag n drop. I have no idea what you mean by "reordering bookmark" and how that differs from what I said

2022-02-11 18:01 UTC, GlassGruber commented
> So that's what I meant when I said drag n drop. I have no idea what you mean by "reordering bookmark" and how that differs from what I said
> * i never use the bookmarks manager

I do sometimes use the bookmark manager and the usability... well is not really the main sell point of the tool IMO. It happens sometimes that I need to rearrange bookmarks that have been saved in weird order or similar. 

> IDK and don't care, I disabled it :) 
Disable first, ask questions later. Sounds like a good plan. 😎

2022-02-11 18:06 UTC, GlassGruber commented
> Wouldn't this be triggered when reordering bookmarks?
> I have no idea what you mean by "reordering bookmark" and how that differs from what I said

Mmm I messed it a bit, I actually really intended a question but that negation morphed it in an assertion, correct phrase is:

Would this be triggered when reordering bookmarks?

Anyway yea, disabled and done.

2022-02-13 10:03 UTC, earthlng requested changes

2022-02-13 10:39 UTC, earthlng approved these changes

2022-02-13 11:15 UTC, merged

2022-02-13 11:40 UTC, crssi commented
❤️